[package]
name = "repomop"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
repomop-core = { workspace = true }
repomop-fs = { workspace = true }
repomop-scanner = { workspace = true }
repomop-tui = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
